subname: file-api
annotations:
  enabled: true
container:
  image: skaillz/phototimelapse-file-api:latest
  ports: 
      singlePort: true
      port: 3001
      targetPort: 3001
  env: []
service:
  type: LoadBalancer
pvc:
  enabled: true
  mountPath: /file-api/uploads
  accessModes: ReadWriteOnce
  storage: 1Gi

