{{ if (eq .Values.pvc.enabled true) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.subname }}-pvc
  labels:
    app: {{ .Values.subname }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
{{ end }}
