name: kubernetes-deploy

on:
  release:
    types: [published]

jobs:
  kubernetes-deploy:
    name: Kubernetes production deployment
    runs-on: ubuntu-latest
    needs: [docker-hub]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y kubectl
          sudo snap install doctl

          # Weird things you have to do to make the snap version work
          mkdir ~/.kube
          sudo snap connect doctl:kube-config

      - name: Login to Cluster
        run: |
          doctl auth init -t ${{ secrets.DIGITALOCEAN_TOKEN }}
          doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER }}

      - name: Deploy
        run: |
          helm upgrade phototimelapse ./helmchart/
